In [26]:
import pandas as pd
import numpy as np

In [11]:
df=pd.read_csv(r'C:\Users\shreyaash mogaveera\MedBot\data\dataset.csv')

In [12]:
#removing space from symptom names
symptom_cols=[col for col in df.columns if col.startswith('Symptom_')]

for col in symptom_cols:
    df[col]=df[col].str.strip()
    df[col]=df[col].str.replace(' ','_')
    df[col]=df[col].str.lower()

In [13]:
#getting all the unique symptoms
all_symptoms=set()
for col in symptom_cols:
    all_symptoms.update(df[col].dropna().unique())
all_symptoms=sorted(list(all_symptoms))

print("total unique symptoms:",len(all_symptoms))
print("\n Sample symptoms:",all_symptoms[:10])

total unique symptoms: 131

 Sample symptoms: ['abdominal_pain', 'abnormal_menstruation', 'acidity', 'acute_liver_failure', 'altered_sensorium', 'anxiety', 'back_pain', 'belly_pain', 'blackheads', 'bladder_discomfort']

In [20]:
#creating binary feature matrix
#1=present, 0=absent
X=pd.DataFrame(0,index=df.index,columns=all_symptoms)
for col in symptom_cols:
    for idx,symptom in df[col].items():
        if pd.notna(symptom) and symptom in X.columns:
            X.loc[idx,symptom]=1

print("feature matrix shape:",X.shape)
print("\nSample") 
X.sample(5)

feature matrix shape: (4920, 131)

Sample

,abdominal_pain,abnormal_menstruation,acidity,acute_liver_failure,altered_sensorium,anxiety,back_pain,belly_pain,blackheads,bladder_discomfort,...,vomiting,watering_from_eyes,weakness_in_limbs,weakness_of_one_body_side,weight_gain,weight_loss,yellow_crust_ooze,yellow_urine,yellowing_of_eyes,yellowish_skin
968,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,1
1225,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
434,0,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3683,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
301,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
#encode the target variable
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(df['Disease'])

print("number of classes:", len(le.classes_))
print("classes:",le.classes_)

number of classes: 41
classes: ['(vertigo) Paroymsal  Positional Vertigo' 'AIDS' 'Acne'
 'Alcoholic hepatitis' 'Allergy' 'Arthritis' 'Bronchial Asthma'
 'Cervical spondylosis' 'Chicken pox' 'Chronic cholestasis' 'Common Cold'
 'Dengue' 'Diabetes ' 'Dimorphic hemmorhoids(piles)' 'Drug Reaction'
 'Fungal infection' 'GERD' 'Gastroenteritis' 'Heart attack' 'Hepatitis B'
 'Hepatitis C' 'Hepatitis D' 'Hepatitis E' 'Hypertension '
 'Hyperthyroidism' 'Hypoglycemia' 'Hypothyroidism' 'Impetigo' 'Jaundice'
 'Malaria' 'Migraine' 'Osteoarthristis' 'Paralysis (brain hemorrhage)'
 'Peptic ulcer diseae' 'Pneumonia' 'Psoriasis' 'Tuberculosis' 'Typhoid'
 'Urinary tract infection' 'Varicose veins' 'hepatitis A']

In [27]:
import joblib
joblib.dump(all_symptoms,'../model/symptom_columns.pkl')
joblib.dump(le,'../model/label_encoder.pkl')

['../model/label_encoder.pkl']

In [31]:
severity=pd.read_csv(r'C:\Users\shreyaash mogaveera\MedBot\data\Symptom-severity.csv')
severity.sample()

                Symptom  weight
99  red_spots_over_body       3

In [32]:
severity['Symptom']=(severity['Symptom'].str.strip().str.replace(' ','_').str.lower())

In [34]:
severity_dict=dict(zip(severity['Symptom'],severity['weight']))

In [35]:
#saving this for app purpose
joblib.dump(severity_dict,'../model/severity_dict.pkl')

['../model/severity_dict.pkl']

In [36]:
X.shape

(4920, 131)

In [37]:
y.shape

(4920,)